### PR TITLE
setup.sh: Adapt permissions for user login journal files

### PR DESCRIPTION
**Pull request by KellerFuchs**

### CODE REVIEW

**Comment by ChickenNuggers** [comment]
lgtm

**Comment by KellerFuchs** [comment]
PS: We don't currently make admins be in the group `adm`.  I think we should, but that's for a later issue.

**Comment by ChickenNuggers** [comment]
They are in the `sudo` group though, aren't they?

**Comment by KellerFuchs** [comment]
Yes.  The `adm` group is quite different, though (as I said, most distros use it to give RO access to logs).

**Pull request merged**
