### PR TITLE
etckeeper: Push to a dedicated branch

### PR DESCRIPTION
**Pull request by KellerFuchs**
This makes `etckeeper` push to `git-infra.hashbang.sh`, on a dedicated branch.
Updates are still pulled from the `master` branch of `shell-etc`, on Github.

This impacts the admin's workflow as follows:
- Nothing changes when deploying updates pulled from `master`: as usual, just to `ansible-playbook shell.yml`.
- When dealing with on-server modifications (typically, security upgrades):
  1. fetch the server branches from `git-infra.hashbang.sh` (`git fetch -a`);
  2. review the changes (typically, did all the servers undergo the same change?);
  3. do a signed merge into master: `git merge -S da1 ny1 sf1 to1`;
  4. `push` to Github.

### CODE REVIEW

**Comment by lrvick** [comment]
LGTM provided git-infra.hashbang.sh is up and running.

**Comment by KellerFuchs** [comment]
@lrvick It already is, and it has your pubkey.
Run `ssh git@git-infra.hashbang.sh` to check.

**Comment by lrvick** [comment]
+1

**Comment by KellerFuchs** [comment]
@lrvick Added a commit

**Pull request merged**
