### PR TITLE
Ignore etc files introduced by apt

### PR DESCRIPTION
**Pull request by mayli**
#164 

**just a draft**, docker image is broken, i didn't test it yet

### CODE REVIEW

**Comment by lrvick** [comment]
You should be able to get a substantially smaller list than that.

This -should- show you all apt-maintained files that we have customized: 
```
dpkg-query -W -f='${Conffiles}\n' '*' | awk 'OFS="  "{print $2,$1}' | LANG=C md5sum -c 2>/dev/null | awk -F': ' '$2 !~ /OK$/{print $1}' | sort | less
```

And then this should spit out all /etc/ files not owned by any package:

```
find /etc -xdev -type f \( -exec grep -xq "{}" /var/lib/dpkg/info/*.list \; -or -print \)
```
This will include generated files, and then ones we specifically maintain.

Between the two we should be able to get a pretty complete list.

From there we can  ``` echo "*" >> .gitignore``` to put git in "whitelist" mode, ```git rm *```, then ```git add -f``` all the non-generated files from the above two lists.

**Comment by lrvick** [comment]
I see merit to this.

The deployed /etc config might differ based on what flavor of debian someone is using, or the target arch (qemu, AMI, etc etc)

I think what is more important is that we track only the specific files that are relevant to our deployment. For all other files, I don't care, as we are just trusting the maintainer.

By only having the changes we actually need it also serves as a reference for others who want to do similar setups, but perhaps on different distros. 

Currently I am totally lost as to what changes are custom vs what changes are system provided anymore.

The deployment issues you mention are easily resolved by removing .git on all the servers and doing a fresh etckeeper init as a one-time thing.

But yes, with a whitelist approach we would not track the configurations or files of any new package unless we want to override something. The scope of this repo then becomes as an -overlay- and much easier to maintain/test/review.

Honestly, are we even reviewing the 10k changes that happen with each apt-get update? Having a lot of things enter a repo that are by nature too long to review in detail is a security hole. We should not be signing anything we are not willing to review every line of and the scale of reviewing every single change made by apt is daunting.

**Comment by KellerFuchs** [comment]
> The deployment issues you mention are easily resolved by removing .git on all the servers and doing a fresh etckeeper init as a one-time thing.

The main issue is 2: Git will error out when we add a new file to the repo that was previously gitignore'd.

> this would eliminate us having the whole extra layer of having all the servers publish their automatd apt-get update changes to internal git servers for merging

Not having any visibility on what is the deployed state on a given server doesn't strike me as a feature.

All in all, I'm not against doing this (not sure what gave you that impression...) but there are major ops/automation issues that needs to be solved...

**Comment by lrvick** [comment]
@KellerFuchs

> The main issue is 2: Git will error out when we add a new file to the repo that was previously gitignore'd.

Not sure I follow here. I have * in my .gitignore in /home and do a setup exactly like I am proposing for /etc. Once you git add -f a file or folder git will maintain memory of that exception. Likewise if we add * to .gitignore today, it won't impact files we have tracked in the past.

**Comment by lrvick** [comment]
Also just to put it on the table:
With the new model we are talking about, is etckeeper still the right tool for the job?

Once we isolate the dozen or so config files for our overlay, we could just have ansible maintain them as a post-apt-get step with service reload triggers as needed.

**Comment by KellerFuchs** [comment]
> > The main issue is 2: Git will error out when we add a new file to the repo that was previously gitignore'd.
>
> Not sure I follow here. I have * in my .gitignore in /home and do a setup exactly like I am proposing for /etc. Once you git add -f a file or folder git will maintain memory of that exception. Likewise if we add * to .gitignore today, it won't impact files we have tracked in the past.

The issue I'm referring to is:
- A file is git-ignore'd
- It gets added to the repository
- `git pull` is ran on a machine where the file exists.

As you may or may not recall, the move to using stow in dotfiles was prompted by similar issues...

**Comment by mayli** [comment]
-> #175

**Pull request closed without merging**
