### PR TITLE
Fix postfix relay after the mail server's fingerprint changed

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by KellerFuchs** [comment]
:sob:

**Comment by KellerFuchs** [comment]
@hashbang/administrators Can someone review the changes I made to @l2dy's PR?

**Comment by l2dy** [comment]
@KellerFuchs OK to merge?

**Comment by KellerFuchs** [comment]
@l2dy Yes it is; I was just hoping another admin would do it because I didn't really have the energy do deal with it.

**Pull request merged**
