### PR TITLE
Add default npm configuration

### LINKED ISSUE #134: `install_node_version` needs to make sure `npm` has a `prefix` variable configured.
https://github.com/hashbang/shell-etc/blob/66913e1c42a2b93e50b40fda18035235efd4cdfb/profile.d/npm.sh

Node requires root to be installed.

```npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/npm',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm"
npm ERR! cwd /home/nullpixel
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules
npm ERR! fstream_path /usr/local/lib/node_modules/npm
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR!```

### PR DESCRIPTION
**Pull request by RyanSquared**
This fixes #134.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Any reason this is system-wide, and not in the default dotfiles?
What happens when a user creates a `~/.npmrc`?

**Comment by RyanSquared** [comment]
> Any reason this is system-wide, and not in the default dotfiles?

This change only affects something that previously was broken for users (the `-g` flag) and doesn't require users to change anything.

> What happens when a user creates a `~/.npmrc`?

If it has values that override the prefix, then `~/.npmrc` values take priority.

**Comment by KellerFuchs** [comment]
@RyanSquared Works for me.

**Comment by drGrove** [comment]
@KellerFuchs if you believe this is ready to merge, can you please change your review?

**Comment by KellerFuchs** [comment]
@drGrove “Works for me” referred to the reason why this is a global thing, and not a dotfiles thing.
The change I requested (missing `.etckeeper` stuff) hasn't happened yes.

**Comment by RyanSquared** [comment]
@KellerFuchs it has now

**Pull request merged**
