### PR TITLE
Add cron.daily/clean-lurkers

### PR DESCRIPTION
**Pull request by KellerFuchs**
Terminate sessions of users who haven't logged in more than 15 days.

### CODE REVIEW

**Comment by AlissaSquared** [comment]
I think it should be 30 honestly. Opinions?

**Comment by drGrove** [comment]
I agree with @AlissaSquared. Give them 30

**Comment by lrvick** [comment]
30d is fine for now. We can get more aggressive with this if we start hurting for resources.

**Comment by KellerFuchs** [comment]
Done

**Pull request merged**
