### PR TITLE
remove setup.sh, document new update flow

### PR DESCRIPTION
**Pull request by lrvick**
Currently, the way of making changes to etc, is go do it in prod, hope it does not break everything, then spread it to other systems.

This is really bad practice, and I have been trying to come up with a way of doing local dev. Now that shell-server is broken out into its own repo and has a working docker container, the local workflow documented here is possible and allows for signing and PRs.

Totally open to alternative non-docker local development paths, vagrant, etc. Docker is just what I am the most familiar/comfortable with for use cases like this so I went for it.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
The “eyebrow-raising” options are still not explained properly:
- Why would I want to GPG-sign from inside the container?
- Why would I want to push from inside the container?  
  (Also, you didn't document that the SSH key needs to already be loaded in the agent)

Also, how does the testing even works without a LDAP/userdb/whatever to talk to?

**Comment by KellerFuchs** [comment]
PS: This seems to complement hashbang/hashbang#10 without any bad interaction.  The only change required should be where the changes are pushed once ready for PR/test/review.

**Comment by lrvick** [comment]
@KellerFuchs see updated docs.

**Comment by lrvick** [comment]
Directed people to hashbang/hashbang for more complex changes which https://github.com/hashbang/hashbang/pull/15 is the start of providing tooling for.

**Comment by KellerFuchs** [comment]
@lrvick Seems good, though recommending to sign all commits with an interactive rebase is not needed (the head commit being signed brings all the same guarantees).

**Pull request merged**
