### PR TITLE
etckeeper: Add metadata tests and CI integration

### PR DESCRIPTION
**Pull request by KellerFuchs**
- [x] Add a simple script to apply etckeeper metadata (without ownership information).
- [x] Add a script that checks if the metadata is consistent with the contents of the Git workdir.
- [x] Fix the current metadata (ordering according to `LANG=C`, missing directories)

### CODE REVIEW

**Comment by KellerFuchs** [comment]
OK, something is wrong as `check.sh` doesn't fail on Travis, whereas it does locally.

**Comment by KellerFuchs** [comment]
Lovely...
Travis environments are so obsolete that we can't easily run non-stupid versions of etckeeper.

**Comment by RyanSquared** [comment]
Perhaps CircleCI would work better for this?

**Comment by KellerFuchs** [comment]
@RyanSquared I've looked at a couple of alternative, and pretty much shortlisted CircleCI and DroneCI.
Will have a stab at it again a bit later, might split the PR in the test scripts and the CI work.

**Comment by RyanSquared** [comment]
Closing as priority is instead to move to Ansible and get rid of etckeeper

**Pull request closed without merging**
