### PR TITLE
Configure msmtp for use as sendmail(1)

### PR DESCRIPTION
**Pull request by KellerFuchs**
Part of #86. Rationale described [there](https://github.com/hashbang/shell-etc/issues/86#issuecomment-221954226).
~~Will need to be followed by `apt install msmtp-mta` (which provides the `sendmail` symlink).~~

Needs to be followed by setting `/usr/sbin/sendmail` to be `msmtp`.  The *least wrong* way I found how to do this is to set a `dpkg-divert` to get Postfix's binary out of the way, then create the symlink (and adapt `setup.sh` to do this when setting up a new box).

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Note: `msmtp-mta` and `postfix` are flagged as in conflict, because they both provide `/usr/sbin/sendmail`.
I think the cleanest/most robust way to deal with that is with [`dpkg-divert(8)`](http://linux.die.net/man/8/dpkg-divert):
```
dpkg-divert --package wibble --divert /usr/bin/example.foo --rename /usr/bin/example
```

**Comment by KellerFuchs** [comment]
@hashbang/administrators Are you fine with this way of dealing with it?

I'm not mega-happy, but it should get the job done reliably.

**Comment by ChickenNuggers** [comment]
Lgtm👍

**Comment by KellerFuchs** [comment]
@ChickenNuggers OK, trying deployment on `to1`.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Done and tested.
@ChickenNuggers Thanks for double-checking me.

**Pull request merged**
