### PR TITLE
etckeeper: Do not prompt for password on push

### PR DESCRIPTION
**Pull request by KellerFuchs**
- Passes an option to SSH to forbid prompting for a password
- Does not ignore push failures

### CODE REVIEW

**Comment by daurnimator** [comment]
:-1: I'd rather just turn off `PUSH_REMOTE`

**Comment by KellerFuchs** [comment]
@daurnimator What would be your suggested low for installing packages, then?

Also, simply turning off `PUSH_REMOTE` means that commits are silently made that will trip up the automation later.

**Comment by daurnimator** [comment]
> @daurnimator What would be your suggested flow for installing packages, then?

Manual `etckeeper vcs push`

**Comment by KellerFuchs** [comment]
More like `etckeeper vcs push git@github.com:hashbang/shell-etc.git` currently...
@daurnimator What would be the expected benefit and how do we unsure that we don't just get commits waiting silently until the next run of `sync.yml`?

**Comment by daurnimator** [comment]
> More like etckeeper vcs push git@github.com:hashbang/shell-etc.git currently...

You can still set the origin. just `etckeeper vcs push` should be sufficient.

> @daurnimator What would be the expected benefit and how do we ensure that we don't get commits waiting silently until the next run of sync.yml?

etckeeper often makes automatic commits that I immediately back out. I *count* on the push failing.

But also, I don't have ssh agent turned on. I pull to a local dir, then push from there.

**Comment by KellerFuchs** [comment]
> > More like etckeeper vcs push git@github.com:hashbang/shell-etc.git currently...
>
> You can still set the origin. just etckeeper vcs push should be sufficient.

Sure, I just meant it would have to be implemented.

> etckeeper often makes automatic commits that I immediately back out. I count on the push failing.

Except that the current behaviour is not failing, it is hanging forever...
Can we agree to merge that, since it is needed in both cases, and open a new issue for improving the etckeeper workflow?

**Comment by daurnimator** [comment]
> Except that the current behaviour is not failing, it is hanging forever...

It doesn't for me?
It just says permission denied and fails out.

**Comment by KellerFuchs** [comment]
Right, it only hangs when the commit is triggered by ansible.
In any case, I believe we both agree `PasswordAuthentication=no` is the right thing to do in that case, regardless of what we decide to use as a better workflow in the future.

**Comment by KellerFuchs** [comment]
@daurnimator Ping?

**Comment by KellerFuchs** [comment]
@daurnimator Should I consider this approved by timeout?  :-/

**Comment by KellerFuchs** [comment]
@hashbang/administrators Ping.  Need someone to approve.

**Comment by daurnimator** [comment]
I still think this is a bad idea.

> In any case, I believe we both agree PasswordAuthentication=no is the right thing to do in that case, regardless of what we decide to use as a better workflow in the future.

We do? I don't see the point in enabling this option.
If it fixes your problem, I think it fixes a symptom rather than a cause.

> @daurnimator Should I consider this approved by timeout? :-/

I would suggest we should never do that unless it reaches a time scale of *months*. Not 3 days.

**Comment by KellerFuchs** [comment]
> I would suggest we should never do that unless it reaches a time scale of months. Not 3 days.

The “approved by timeout” comment was somewhat unwarranted (though it is highly frustrating to have a number of changes stuck on review), but *months* sounds crazy.
Also, non of the questions I asked you were answered.

> We do? I don't see the point in enabling this option.
> If it fixes your problem, I think it fixes a symptom rather than a cause.

The point is, sometimes commits are produced and `99push` makes Ansible hang forever.
This makes it fail reliably instead.

Frankly, I have the impression you don't like the “autopush” workflow, and are basically stonewalling this PR based on that.
This is fair enough, I have a number of issues with it too. However, this PR is about fixing a specific issue, and discussion of a replacement workflow should go, IMO, in another issue.

**Comment by KellerFuchs** [comment]
@daurnimator Sorry if that previous message was a tad grumpy, but I would still like this issue to move forward and the workflow discussion to go to another issue, if you don't mind  :3

**Comment by KellerFuchs** [comment]
@hashbang/administrators This is still an issue.

@daurnimator Can we revisit that *without* getting into a discussion about redoing entirely how we deal with `/etc` and packages install/updates?
While I agree that it can be improved, this is way out of scope for this PR: it is only meant to solve something that is currently an issue.

**Comment by KellerFuchs** [comment]
This issue is still occuring.  I suggest setting a timeout on it for the end of the month.

**Comment by KellerFuchs** [comment]
Halfway there ...

**Comment by KellerFuchs** [comment]
I can't believe everybody is ignoring this so hard I will *actually* merge by timeout.
Seriously, people ...

**Comment by lrvick** [comment]
I am really not sure what your setup is like that your agent does not do the right thing and hangs, but we are never going to want to use plain-text passwords anyway and it ever asking is just going to hang automation forever instead of erroring out as it should. If we have hit the situation where a password would be prompted, better to just fail imo which is what I understand this will do.

If that is the case, I say merge it.

**Comment by KellerFuchs** [comment]
@lrvick Basically, in some cases, there is no SSH agent (run triggered through Ansible) and for whatever reason the Github SSHd let the authentication fallback to `password` (or perhaps `keyboard-interactive`, I'm not entirely sure).
Then, `git` blocks on tty input, effectively freezing `etckeeper`, `apt` and `ansible` (in reverse call order).

**Comment by daurnimator** [comment]
> @lrvick Basically, in some cases, there is no SSH agent (run triggered through Ansible) and for whatever reason the Github SSHd let the authentication fallback to password (or perhaps keyboard-interactive, I'm not entirely sure).

I thought this is because our default remote is https; not SSH?
Perhaps all that needs to change is the origin?

**Comment by daurnimator** [comment]
> I thought this is because our default remote is https; not SSH?
> Perhaps all that needs to change is the origin?

Yep:

```
$ sudo etckeeper vcs remote -v
origin	https://github.com/hashbang/shell-etc.git (fetch)
origin	https://github.com/hashbang/shell-etc.git (push)
```

**Comment by KellerFuchs** [comment]
Yay, wrong fix and stuff.
Well, it's nap time for me in any case ...

**Comment by KellerFuchs** [comment]
@daurnimator Actually, no: pushes are not made to `origin`, but to [`PUSH_REMOTE`](https://github.com/hashbang/shell-etc/blob/b28c7b3cde1fb40729782c613940c4929fdc3fdc/etckeeper/etckeeper.conf#L43), which indeed uses SSH.

**Pull request merged**
