### PR TITLE
Automatically refresh keyring

### PR DESCRIPTION
**Pull request by KellerFuchs**
This should avoid the issues we recently had.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@daurnimator I will do so (and update the `shell.yml` playbook) once this is merged and deployed.

**Comment by KellerFuchs** [comment]
@hashbang/administrators As a quick reminder, I can't currently sign and merge this, so I need one of you to do it.

**Comment by DeviaVir** [comment]
@KellerFuchs not too sure about the deploy path, if you need me to do that as well please RTFM me on what to run

**Comment by KellerFuchs** [comment]
@DeviaVir The deploy only involves running `shell.yml`, usually.

However, I didn't notice but you snuck in a commit that changed your key.
Since the shell servers check the signature on the repo *based on the keys they already trust*, it means the signature was rejected and I had to do mildly-acrobatic workarounds instead...

**Pull request merged**
