### PR TITLE
skel: Support git submodules in dotfiles

### PR DESCRIPTION
**Pull request by KellerFuchs**
This makes https://github.com/hashbang/dotfiles/pull/17 possible.

### CODE REVIEW

**Comment by daurnimator** [comment]
hmm, I don't know how to feel about this. git submodules are always a mess; no one ever gets them working on the first go. And once they're in there, they're hard to remove. i.e. I guarantee this change will result in many questions to us in the irc channel...

**Comment by jhass** [comment]
Agreed, `git subtree` might be the better option for these usecases here.

**Comment by KellerFuchs** [comment]
@jhass Regarding git subtrees, they do not fit given that the files do not have the names we need/want in `grml-etc-core` (`zshrc` vs `.zshrc` and so on)
Note that those names are required by the current setup which has `~` be directly a clone of hashbang/dotfiles.

**Comment by jhass** [comment]
I don't see how submodules make any difference regarding that issue.

**Comment by KellerFuchs** [comment]
@jhass Please have a look at https://github.com/hashbang/dotfiles/issues/17
I think it would be helpful that we discuss the suggested change, rather that submodules merits in general...

**Comment by jhass** [comment]
I did.

**Comment by KellerFuchs** [comment]
Ok, then I just don't get your subtree suggestion.

As far as I understood, you wanted us to merge changes from grml-etc-core rather than have them as a submodule and overlay our own changes over it using `.zshrc`. If not, please be more explicit.

**Comment by jhass** [comment]
`git subtree` merges a remote repository into a folder of the local repository by rewriting history of the remote repository in a reproducible manner. It has options to squash the remote history into single commits for each merge. There's no further state required, all the state for `git subtree` to work is encoded into the "merge" commits (which aren't true merge commits). That means if you clone a repo, the subtree is directly there, no further initialization necessary. This also works well with all exports and other operations, since the remote repository ends up as regular commits instead of merely as an external reference some tools won't understand. It also even allows to do commits on the subtree and later export (a properly rewritten) version to the remote repository. The clear disadvantage is that it blows up the size of the local repository a lot more.

**Comment by KellerFuchs** [comment]
I am aware of what `git subtree` does.  What I am not aware of is what you were suggesting we do with it, since we are _again_ ending up commenting on git features in the abstract, rather than discussing concrete proposals.

**Comment by jhass** [comment]
I thought it's obvious, use a subtree not a submodule in https://github.com/hashbang/dotfiles/pull/17 Didn't using a submodule there motivate this PR?

**Comment by KellerFuchs** [comment]
Quick recap of the arguments stated on IRC:

- In favor of subtrees: it makes updates easier for the user (they can just git pull).
- In favor of git submodules:
  - they seem more widely used & documented;
  - they are nicer for actually working on dotfiles;
  - they make it easy for a user to pull in the latest version of grml-etc-core, without risking to diverge from hashbang/dotfiles and get merge conflicts in the future.

**Comment by ChickenNuggers** [comment]
Any updates on this?

**Comment by KellerFuchs** [comment]
Seems not.
@ChickenNuggers @jhass Anyone against merging?

**Comment by ChickenNuggers** [comment]
No objection.

**Comment by daurnimator** [comment]
I guess you can merge it; but I'd prefer that we discouraged use of submodules. They're a bad pattern that is far too popular (because subtrees are newer)

**Comment by KellerFuchs** [comment]
> They're a bad pattern that is far too popular (because subtrees are newer)

@daurnimator That's my issue: I summarised the pros and cons of each solution, noone commented on that, and I've yet to hear why submodules are a bad pattern (except that subtrees are newer, which isn't quite an argument ...)

**Comment by KellerFuchs** [comment]
@daurnimator Ping?  What are your specific concerns?

**Comment by KellerFuchs** [comment]
Approved by @AlissaSquared, myself and timeout.

**Pull request merged**
