### PR TITLE
apt: Pull golang from jessie-backports

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by daurnimator** [comment]
What about the [golang package](https://packages.debian.org/en/jessie-backports/golang) itself?

I think I'd prefer you spelled out the relevant packages rather than using a wildcard.

**Comment by l2dy** [comment]
`golang` is not in https://github.com/hashbang/shell-etc/blob/master/packages.txt.
```
$ dpkg -l | grep golang
ii  golang-go                             2:1.3.3-1                            amd64        Go programming language compiler
ii  golang-go-linux-amd64                 2:1.3.3-1                            amd64        Go standard library compiled for linux_amd64
ii  golang-src                            2:1.3.3-1                            amd64        Go programming language compiler - source files
```

**Comment by daurnimator** [comment]
I thought it might matter if some package brought in 'golang' as a dependency?

**Comment by l2dy** [comment]
Updated. I still prefer using a wildcard.

**Comment by KellerFuchs** [comment]
I think having the wildcard in that case makes sense; otherwise, we would potentially have an inconsistent mix of Go 1.7 and 1.3.

**Comment by KellerFuchs** [comment]
@l2dy Sorry this is kinda stalled right now, as I've not been available to deal with some issues related to package deployments.
I will be getting to this as soon as I can, though.  :)

**Comment by lrvick** [comment]
@KellerFuchs We are good to merge this now yeah?

**Comment by KellerFuchs** [comment]
@lrvick Should be.

**Comment by l2dy** [comment]
Should this be closed in favor of update to Debian 9 Stretch?

**Comment by RyanSquared** [comment]
Depends on when we plan on updating. I didn't even know stretch was ready until last night.

**Comment by dpflug** [comment]
Am I correct in assuming that any upgrade to Stretch is waiting on our local testing setup (I think the issue # is hashbang/shell-server#43?), so we should merge this now rather than waiting on local testing being ready Soon(tm)?

**Comment by RyanSquared** [comment]
> Am I correct in assuming that any upgrade to Stretch is waiting on our local testing setup

Pretty much everything is.

> so we should merge this now rather than waiting on local testing being ready Soon(tm)?

I dunno. Some people want to wait until we're fully migrated to continue things that aren't security-critical.

**Comment by l2dy** [comment]
I'll just install go in `$HOME`.

**Pull request closed without merging**
