### PR TITLE
Add support for Node.js PATH variable based off of ~/.npmrc

### PR DESCRIPTION
**Pull request by ChickenNuggers**
Sets `$PATH` based off of the Node.js automatic path detection. This pull request also fixes the mode for `luarocks_aliases.sh`, removing the executability of the file (It's not needed).

### CODE REVIEW

**Comment by KellerFuchs** [comment]
I think that belongs in `dotfiles`.
In particular, that would avoid auto-creating a dotfile withing a user's homedir.

**Comment by ChickenNuggers** [comment]
We all agreed that this belongs in `shell-etc`. If this gets merged, what happens with the people who _don't_ have a ~/.npmrc? They'll have the system setup but not the local one.

**Comment by KellerFuchs** [comment]
@ChickenNuggers Users who want to use `npm` would indeed have to update their dotfiles.
I don't think that's much of an issue, whereas silently modifying/creating dotfiles for users *is*:

1. It means that users who indeed use the git versionning for their dotfiles get screwed over (they silently get a new file that won't get noticed/commited, thanks to `.gitignore`).
2. It makes it impossible, in the future, to change that setting: how do you know whether the `.npmrc` file was created for the user (and thus should not be touched) or not?
3. This is confusing/unexpected behaviour, and I thought providing users with a somewhat-standard environment is a thing.

**Comment by KellerFuchs** [comment]
Also, the mode change should be in a different commit  ;-)

**Comment by ChickenNuggers** [comment]
I'll add a default .npmrc but the path setting will stay in `/etc`

**Comment by KellerFuchs** [comment]
Works for me

**Comment by ChickenNuggers** [comment]
hey i forgot about this
ima fix it up a bit

**Pull request closed without merging**
