### PR TITLE
ssh: Allow binding non-local sockets

### PR DESCRIPTION
**Pull request by RyanSquared**

### CODE REVIEW

**Comment by daurnimator** [comment]
> The commit message is so long Github doesn't even display it; what about something like the issue's title?

eh, I don't mind it how it is. I wouldn't pay any attention to when github decides to do line wrapping.

**Comment by KellerFuchs** [comment]
@daurnimator It was more about it not displaying nicely in many places (terminal, github, emacs ...), than about Github in particular; thanks for making m clarify.

More generally, I would argue that having terse, easy-to-understand commit descriptions is useful.

**Comment by daurnimator** [comment]
Why do you need this?

**Comment by RyanSquared** [comment]
@daurnimator i have a thing running on my computer that i want to access from my Chromebook and I can't port forward, this - for now - will let me use ssh's builtin remote ports.

**Comment by KellerFuchs** [comment]
Deployed, and explicitly reloaded the OpenSSH config with `ansible shell_servers -m service -a 'name=ssh state=reloaded'`.

**Pull request merged**
