### PR TITLE
Add luarocks /etc/profile configuration

### PR DESCRIPTION
**Pull request by ChickenNuggers**
Adds aliases and Lua paths

### CODE REVIEW

**Comment by daurnimator** [comment]
New files need to be added to `.etckeeper`

**Comment by daurnimator** [comment]
Wrong filename in .etckeeper (lua_aliases.sh vs luarocks_aliases.sh)

**Comment by KellerFuchs** [comment]
This is missing a ZSH equivalent.

**Comment by AlissaSquared** [comment]
I thought this was ZSH compatible by being in profile.d ?

On Sat, Mar 5, 2016 at 2:30 PM The Fox in the Shell <
notifications@github.com> wrote:

> This is missing a ZSH equivalent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/shell-etc/pull/78#issuecomment-192729525>.
>
-- 

Charles Heywood <vandor2012@gmail.com>
Programmer :: Scripter :: Designer :: Administrator
https://github.com/ChickenNuggers

**Comment by daurnimator** [comment]
> I thought this was ZSH compatible by being in profile.d ?

This is a default on arch linux, but not AFAIK on the shell servers.
/etc/zsh/zprofile contains:
```
emulate sh -c 'source /etc/profile'
```

**Comment by KellerFuchs** [comment]
Looks good to me.

**Comment by daurnimator** [comment]
Merged but not deployed. Happy to have this deployed next time anyone runs sync.

**Pull request merged**
