### PR TITLE
setup.sh: Turn on logging to disk

### LINKED ISSUE #68: User journals
At the moment users do not have journals.
This means logs from their systemd units disappear into the aether.

### PR DESCRIPTION
**Pull request by daurnimator**
Closes #68

### CODE REVIEW

**Comment by KellerFuchs** [comment]
The `systemd-tmpfiles` invocation creates all the configured directory in `/var/log/journal` but we don't have any in `/etc/tmpfiles.d`.
Did you forget to add something to the PR?

**Comment by daurnimator** [comment]
It already comes in the tmpfiles config:
```
$ grep /var/log/j /usr/lib/tmpfiles.d/* 
/usr/lib/tmpfiles.d/systemd.conf:z /var/log/journal 2755 root systemd-journal - -
/usr/lib/tmpfiles.d/systemd.conf:z /var/log/journal/%m 2755 root systemd-journal - -
```

**Comment by daurnimator** [comment]
The thing about this PR is I'm not sure if we can rely on `systemd-tmpfiles` and `pkill` being installed at this point.
IIRC `setup.sh` is designed to be called by a blank debian install from all major cloud providers?

**Comment by KellerFuchs** [comment]
On Debian Jessie, `systemd-tmpfiles` comes from the `systemd` package.
Looks good to me.

**Comment by daurnimator** [comment]
mmmk. I usually don't like to merge things without testing them first (and I don't know how to test this)

**Comment by KellerFuchs** [comment]
I tested in a debootstrap chroot before merging  ;-)

**Pull request merged**
